spring.application.name=FileProcessor


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


file.input.path=C:\Users\dell\Downloads\New folder\File\input
file.processed.path=C:\Users\dell\Downloads\New folder\File\processed
file.failed.path=C:\Users\dell\Downloads\New folder\File\failed